---
kind: pipeline
name: default

steps:
  - name: test
    image: alpine:3.9
    commands:
      - var tag=git describe --tags
      - echo $tag
    when:
      branch:
        - master
trigger:
  branch:
    - master