---
kind: pipeline
name: default

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags
      - tag=`git describe --tags`
      - export CTAG=$tag

  - name: test
    image: alpine:3.9
    commands:
      - echo $CTAG
      - echo $tag
    when:
      branch:
        - master
trigger:
  branch:
    - master