---
kind: pipeline
name: default

clone:
  disable: true

steps:
#  - name: fetch
#    image: alpine/git
#    commands:
#      - git fetch --tags
#      - tag=`git describe --tags`

 - name: test
   image: alpine:3.9
   secrets: [ test ]
   commands:
     - echo dev
     - echo $${DRONE_TAG=latest}
   when:
     branch:
       - master
#     event:
#       - tag

#  - name: docker
#    image: plugins/docker
#    settings:
#      registry: registry:5000
#      repo: registry:5000
##      force_tag: true
#      use_cache: true
#      auto_tag: true
##      auto_tag_suffix: linux-amd64
#    volumes:
#      - name: docker
#        path: /var/lib/docker

trigger:
  branch:
    - master